import { afterEach, describe, expect, it, vi } from "vitest";

afterEach(() => {
  vi.resetModules();
  vi.unstubAllEnvs();
});

async function readEnabled() {
  const { isBrowserTestModeEnabled } =
    await import("@/lib/browser-test-fixture");
  return isBrowserTestModeEnabled();
}

async function readFixtureIdentity(
  runId: string,
  tenantId: string,
  userId: string,
) {
  const { isBrowserTestFixtureIdentity } =
    await import("@/lib/browser-test-fixture");
  return isBrowserTestFixtureIdentity({ runId, tenantId, userId });
}

describe("browser test fixture mode", () => {
  it("requires the explicit local opt-in", async () => {
    vi.stubEnv("NODE_ENV", "development");
    vi.stubEnv("BROWSER_TEST_MODE", "");
    vi.stubEnv("DATABASE_URL", "postgresql://test.example/browser-test");
    vi.stubEnv(
      "BROWSER_TEST_DATABASE_URL",
      "postgresql://test.example/browser-test",
    );

    expect(await readEnabled()).toBe(false);
  });

  it("enables the fixture only with the expected development flag and explicit test database", async () => {
    vi.stubEnv("NODE_ENV", "development");
    vi.stubEnv("BROWSER_TEST_MODE", "enabled");
    vi.stubEnv("DATABASE_URL", "postgresql://test.example/browser-test");
    vi.stubEnv(
      "BROWSER_TEST_DATABASE_URL",
      "postgresql://test.example/browser-test",
    );

    expect(await readEnabled()).toBe(true);
  });

  it("refuses an enabled flag when the runtime database was not explicitly designated", async () => {
    vi.stubEnv("NODE_ENV", "development");
    vi.stubEnv("BROWSER_TEST_MODE", "enabled");
    vi.stubEnv("DATABASE_URL", "postgresql://production.example/artwork-bank");
    vi.stubEnv(
      "BROWSER_TEST_DATABASE_URL",
      "postgresql://test.example/browser-test",
    );

    expect(await readEnabled()).toBe(false);
  });

  it("always refuses the fixture in production", async () => {
    vi.stubEnv("NODE_ENV", "production");
    vi.stubEnv("BROWSER_TEST_MODE", "enabled");
    vi.stubEnv("DATABASE_URL", "postgresql://test.example/browser-test");
    vi.stubEnv(
      "BROWSER_TEST_DATABASE_URL",
      "postgresql://test.example/browser-test",
    );

    expect(await readEnabled()).toBe(false);
  });

  it("accepts cleanup only for the exact fixture IDs generated by its run", async () => {
    const runId = "run-a";

    expect(
      await readFixtureIdentity(
        runId,
        `browser-test-tenant-${runId}`,
        `browser-test-user-${runId}`,
      ),
    ).toBe(true);
    expect(
      await readFixtureIdentity(
        runId,
        "browser-test-tenant-run-b",
        `browser-test-user-${runId}`,
      ),
    ).toBe(false);
  });
});